[project]
name = "caro-website"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sindre Veum", email = "sindreveum@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
caro-website = "caro_website:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
